In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000


In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5145, 125, 9345, 1817],
 [5145, 125, 9345, 7957],
 [5145, 2781, 9345, 5345],
 [5067, 4484, 643, 1354, 1484],
 [5067, 4484, 643, 1354, 5253],
 [657, 5145, 1682, 9345, 9154],
 [9010, 5151, 3355, 1354]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5145  125 9345 1817]
 [   0    0    0    0 5145  125 9345 7957]
 [   0    0    0    0 5145 2781 9345 5345]
 [   0    0    0 5067 4484  643 1354 1484]
 [   0    0    0 5067 4484  643 1354 5253]
 [   0    0    0  657 5145 1682 9345 9154]
 [   0    0    0    0 9010 5151 3355 1354]]


In [9]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 199ms/step


array([[[-0.03420942, -0.02982713,  0.02322333,  0.00217794,
          0.01917506, -0.02881476, -0.04676889,  0.00052045,
          0.02943981, -0.00154775],
        [-0.03420942, -0.02982713,  0.02322333,  0.00217794,
          0.01917506, -0.02881476, -0.04676889,  0.00052045,
          0.02943981, -0.00154775],
        [-0.03420942, -0.02982713,  0.02322333,  0.00217794,
          0.01917506, -0.02881476, -0.04676889,  0.00052045,
          0.02943981, -0.00154775],
        [-0.03420942, -0.02982713,  0.02322333,  0.00217794,
          0.01917506, -0.02881476, -0.04676889,  0.00052045,
          0.02943981, -0.00154775],
        [-0.01701085, -0.00055907,  0.04271269,  0.03192357,
          0.03136469,  0.04392332,  0.03586647,  0.02152008,
          0.01896086, -0.01638794],
        [ 0.01504321, -0.0055436 , -0.01087727,  0.02240096,
         -0.03362547,  0.02089835, -0.03654741,  0.0278323 ,
         -0.02599227,  0.00780628],
        [-0.01543939, -0.02303029, -0.04154277,  0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 5145,  125, 9345, 1817])

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 50ms/step


array([[-0.03420942, -0.02982713,  0.02322333,  0.00217794,  0.01917506,
        -0.02881476, -0.04676889,  0.00052045,  0.02943981, -0.00154775],
       [-0.03420942, -0.02982713,  0.02322333,  0.00217794,  0.01917506,
        -0.02881476, -0.04676889,  0.00052045,  0.02943981, -0.00154775],
       [-0.03420942, -0.02982713,  0.02322333,  0.00217794,  0.01917506,
        -0.02881476, -0.04676889,  0.00052045,  0.02943981, -0.00154775],
       [-0.03420942, -0.02982713,  0.02322333,  0.00217794,  0.01917506,
        -0.02881476, -0.04676889,  0.00052045,  0.02943981, -0.00154775],
       [-0.01701085, -0.00055907,  0.04271269,  0.03192357,  0.03136469,
         0.04392332,  0.03586647,  0.02152008,  0.01896086, -0.01638794],
       [ 0.01504321, -0.0055436 , -0.01087727,  0.02240096, -0.03362547,
         0.02089835, -0.03654741,  0.0278323 , -0.02599227,  0.00780628],
       [-0.01543939, -0.02303029, -0.04154277,  0.00240958, -0.01614338,
         0.00769588,  0.03027062, -0.03111949